// Re-export the auto-generated Wails bindings with TypeScript types.
// The bindings are regenerated by the Wails Vite plugin during dev/build
// and live in frontend/bindings/gugacode/.
import * as FileServiceBindings from "../../bindings/gugacode/services/fileservice.js";
import * as ProjectServiceBindings from "../../bindings/gugacode/services/projectservice.js";
import * as SettingsServiceBindings from "../../bindings/gugacode/services/settingsservice.js";
import * as WindowServiceBindings from "../../bindings/gugacode/services/windowservice.js";
import * as TerminalServiceBindings from "../../bindings/gugacode/services/terminalservice.js";
import * as AIServiceBindings from "../../bindings/gugacode/services/aiservice.js";
import * as GitServiceBindings from "../../bindings/gugacode/services/gitservice.js";
import * as SearchServiceBindings from "../../bindings/gugacode/services/searchservice.js";
import * as ConversationServiceBindings from "../../bindings/gugacode/services/conversationservice.js";
import * as TaskServiceBindings from "../../bindings/gugacode/services/taskservice.js";
import * as WorkflowServiceBindings from "../../bindings/gugacode/services/workflowservice.js";
import * as AgentServiceBindings from "../../bindings/gugacode/services/agentservice.js";
import * as RulesServiceBindings from "../../bindings/gugacode/services/rulesservice.js";
import * as LogLevelServiceBindings from "../../bindings/gugacode/services/loglevelservice.js";
import * as PluginServiceBindings from "../../bindings/gugacode/services/pluginservice.js";
import * as ProfileServiceBindings from "../../bindings/gugacode/services/profileservice.js";
import * as LayoutServiceBindings from "../../bindings/gugacode/services/layoutservice.js";
import type { DirEntry, Project, Settings, ChatMessage, GitFileChange, BranchInfo, SearchResult, Conversation, PresetMeta, PresetFile, PresetWithSource, CompletionRequest, CompletionResponse, RawCompletionResponse, BranchRef, ReplaceResult, TaskDef, WorkflowDef, WorkflowValidationResult, ExecResult, CommandCheck, RulesFile, RulesFileCandidate, RulesConfig, RulesCandidateConfig, PluginInfo, ProfileInfo, ProfileExport, SecretInfo } from "@/types";

export const fileService = {
  listDirectory: (path: string) =>
    FileServiceBindings.ListDirectory(path) as Promise<DirEntry[]>,
  // Plan 55: Quick Open — recursive file listing respecting .gitignore.
  listAllFiles: (rootPath: string) =>
    FileServiceBindings.ListAllFiles(rootPath) as Promise<string[]>,
  readFile: (path: string) =>
    FileServiceBindings.ReadFile(path) as Promise<string>,
  writeFile: (path: string, content: string) =>
    FileServiceBindings.WriteFile(path, content) as Promise<void>,
  createFile: (path: string) =>
    FileServiceBindings.CreateFile(path) as Promise<void>,
  createDirectory: (path: string) =>
    FileServiceBindings.CreateDirectory(path) as Promise<void>,
  deletePath: (path: string) =>
    FileServiceBindings.DeletePath(path) as Promise<void>,
  renamePath: (oldPath: string, newPath: string) =>
    FileServiceBindings.RenamePath(oldPath, newPath) as Promise<void>,
  pickDirectory: () =>
    FileServiceBindings.PickDirectory() as Promise<string>,
  revealInOS: (path: string) =>
    FileServiceBindings.RevealInOS(path) as Promise<void>,
};

export const projectService = {
  getRecentProjects: () =>
    ProjectServiceBindings.GetRecentProjects() as Promise<Project[]>,
  addProject: (path: string) =>
    ProjectServiceBindings.AddProject(path) as Promise<Project>,
  removeProject: (id: string) =>
    ProjectServiceBindings.RemoveProject(id) as Promise<void>,
};

export const settingsService = {
  loadSettings: () =>
    SettingsServiceBindings.LoadSettings() as Promise<Settings>,
  saveSettings: (settings: Settings) =>
    SettingsServiceBindings.SaveSettings(settings as unknown as Parameters<typeof SettingsServiceBindings.SaveSettings>[0]) as Promise<void>,
  isAPIKeyEncryptedOnDisk: () =>
    SettingsServiceBindings.IsAPIKeyEncryptedOnDisk() as Promise<boolean>,
  getAPIKeyStorageMethod: () =>
    SettingsServiceBindings.GetAPIKeyStorageMethod() as Promise<string>,
  // N-49: list/delete keyring entries for orphan cleanup.
  listSecrets: () =>
    SettingsServiceBindings.ListSecrets() as Promise<SecretInfo[]>,
  deleteSecret: (account: string) =>
    SettingsServiceBindings.DeleteSecret(account) as Promise<void>,
};

export const windowService = {
  minimise: () => WindowServiceBindings.Minimise(),
  maximise: () => WindowServiceBindings.Maximise(),
  // N-152: 标题栏放大/还原按钮共用一个控件，调用 ToggleMaximise 切换状态。
  toggleMaximise: () => WindowServiceBindings.ToggleMaximise(),
  // 查询当前窗口是否已最大化（用于初始化图标状态）。
  isMaximised: () => WindowServiceBindings.IsMaximised() as Promise<boolean>,
  close: () => WindowServiceBindings.Close(),
  toggleFullscreen: () => WindowServiceBindings.ToggleFullscreen(),
  setTitle: (title: string) => WindowServiceBindings.SetTitle(title),
};

export const terminalService = {
  start: (workingDir: string) =>
    TerminalServiceBindings.Start(workingDir) as Promise<void>,
  write: (input: string) =>
    TerminalServiceBindings.Write(input) as Promise<void>,
  kill: () => TerminalServiceBindings.Kill() as Promise<void>,
  isRunning: () =>
    TerminalServiceBindings.IsRunning() as Promise<boolean>,
  resize: (cols: number, rows: number) =>
    TerminalServiceBindings.Resize(cols, rows) as Promise<void>,
  startSession: (id: string, workingDir: string, shell: string) =>
    TerminalServiceBindings.StartSession(id, workingDir, shell) as Promise<void>,
  killSession: (id: string) =>
    TerminalServiceBindings.KillSession(id) as Promise<void>,
  writeSession: (id: string, input: string) =>
    TerminalServiceBindings.WriteSession(id, input) as Promise<void>,
  resizeSession: (id: string, cols: number, rows: number) =>
    TerminalServiceBindings.ResizeSession(id, cols, rows) as Promise<void>,
  isSessionRunning: (id: string) =>
    TerminalServiceBindings.IsSessionRunning(id) as Promise<boolean>,
  listSessions: () =>
    TerminalServiceBindings.ListSessions() as Promise<string[]>,
};

export const aiService = {
  setConfig: (config: {
    apiKey: string;
    baseUrl: string;
    model: string;
    systemPrompt?: string;
    agentSystemPrompt?: string;
    conversationTitlePrompt?: string;
    inlineCompletionPrompt?: string;
    maxTokens?: number;
    contextWindow?: number;
    temperature?: number;
    protocol?: string; // "openai" | "anthropic"
  }) =>
    AIServiceBindings.SetConfig({
      APIKey: config.apiKey,
      BaseURL: config.baseUrl,
      Model: config.model,
      SystemPrompt: config.systemPrompt ?? "",
      AgentSystemPrompt: config.agentSystemPrompt ?? "",
      ConversationTitlePrompt: config.conversationTitlePrompt ?? "",
      InlineCompletionPrompt: config.inlineCompletionPrompt ?? "",
      MaxTokens: config.maxTokens ?? 0,
      ContextWindow: config.contextWindow ?? 0,
      Temperature: config.temperature ?? 0,
      Protocol: config.protocol ?? "",
    }) as Promise<void>,
  send: (messages: ChatMessage[]) =>
    AIServiceBindings.Send(messages) as Promise<{
      Content: string;
      FinishReason: string;
    } | null>,
  startStream: (messages: ChatMessage[]) =>
    AIServiceBindings.StartStream(messages) as Promise<void>,
  stopStream: () =>
    AIServiceBindings.StopStream() as Promise<void>,
  getDefaultSystemPrompt: () =>
    AIServiceBindings.GetDefaultSystemPrompt() as Promise<string>,
  getAgentSystemPrompt: () =>
    AIServiceBindings.GetAgentSystemPrompt() as Promise<string>,
  getSystemPrompt: (name: string) =>
    AIServiceBindings.GetSystemPrompt(name) as Promise<string>,
  getConversationTitlePrompt: () =>
    AIServiceBindings.GetConversationTitlePrompt() as Promise<string>,
  getInlineCompletionSystemPrompt: () =>
    AIServiceBindings.GetInlineCompletionSystemPrompt() as Promise<string>,
  getEffectiveAgentSystemPrompt: () =>
    AIServiceBindings.GetEffectiveAgentSystemPrompt() as Promise<string>,
  getEffectiveConversationTitlePrompt: () =>
    AIServiceBindings.GetEffectiveConversationTitlePrompt() as Promise<string>,
  getEffectiveInlineCompletionPrompt: () =>
    AIServiceBindings.GetEffectiveInlineCompletionPrompt() as Promise<string>,
  generateTitleWithAI: (firstMessage: string) =>
    AIServiceBindings.GenerateTitleWithAI(firstMessage) as Promise<string>,
  getPresetPrompt: (name: string) =>
    AIServiceBindings.GetPresetPrompt(name) as Promise<string>,
  listPresets: () =>
    AIServiceBindings.ListPresets() as Promise<PresetMeta[]>,
  // N-50/Proposal S: Fetch available models from the provider's /v1/models endpoint.
  listModels: (baseURL: string, apiKey: string) =>
    AIServiceBindings.ListModels(baseURL, apiKey) as Promise<string[]>,
  listPresetsWithSource: () =>
    AIServiceBindings.ListPresetsWithSource() as Promise<PresetWithSource[]>,
  saveProjectPreset: (preset: PresetFile) =>
    AIServiceBindings.SaveProjectPreset(preset) as Promise<void>,
  saveUserPreset: (preset: PresetFile) =>
    AIServiceBindings.SaveUserPreset(preset) as Promise<void>,
  deleteProjectPreset: (name: string) =>
    AIServiceBindings.DeleteProjectPreset(name) as Promise<void>,
  deleteUserPreset: (name: string) =>
    AIServiceBindings.DeleteUserPreset(name) as Promise<void>,
  complete: (req: CompletionRequest, signal?: AbortSignal) => {
    // N-43: Preserve the CancellablePromise so the caller can abort the
    // in-flight request. Wails bindings return a CancellablePromise with
    // a .cancelOn(signal) method that binds cancellation to an AbortSignal.
    const cancellable = AIServiceBindings.Complete(req) as Promise<RawCompletionResponse> & {
      cancelOn?: (sig: AbortSignal) => Promise<RawCompletionResponse>;
    };
    if (signal && typeof (cancellable as { cancelOn?: unknown }).cancelOn === "function") {
      cancellable.cancelOn!(signal);
    }
    return cancellable.then((r: RawCompletionResponse) => ({ text: r.Text ?? r.text ?? "" })) as Promise<CompletionResponse>;
  },
};

export const gitService = {
  getStatus: (path: string) =>
    GitServiceBindings.GetStatus(path) as Promise<GitFileChange[]>,
  getBranchInfo: (path: string) =>
    GitServiceBindings.GetBranchInfo(path) as Promise<BranchInfo>,
  stage: (path: string, filePath: string) =>
    GitServiceBindings.Stage(path, filePath) as Promise<void>,
  unstage: (path: string, filePath: string) =>
    GitServiceBindings.Unstage(path, filePath) as Promise<void>,
  commit: (path: string, message: string) =>
    GitServiceBindings.Commit(path, message) as Promise<void>,
  getDiff: (path: string, filePath: string) =>
    GitServiceBindings.GetDiff(path, filePath) as Promise<string>,
  getFullDiff: (path: string) =>
    GitServiceBindings.GetFullDiff(path) as Promise<string>,
  listBranches: (path: string) =>
    GitServiceBindings.ListBranches(path) as Promise<BranchRef[]>,
  createBranch: (path: string, name: string) =>
    GitServiceBindings.CreateBranch(path, name) as Promise<void>,
  checkoutBranch: (path: string, name: string) =>
    GitServiceBindings.CheckoutBranch(path, name) as Promise<void>,
  deleteBranch: (path: string, name: string) =>
    GitServiceBindings.DeleteBranch(path, name) as Promise<void>,
  push: (repoPath: string) =>
    GitServiceBindings.Push(repoPath) as Promise<void>,
  pull: (repoPath: string) =>
    GitServiceBindings.Pull(repoPath) as Promise<void>,
};

export const searchService = {
  search: (root: string, query: string, ignoreCase: boolean) =>
    SearchServiceBindings.Search(root, query, ignoreCase) as Promise<SearchResult[]>,
  replace: (filePath: string, pattern: string, replacement: string, caseSensitive: boolean) =>
    SearchServiceBindings.Replace(filePath, pattern, replacement, caseSensitive) as Promise<ReplaceResult>,
};

export const conversationService = {
  save: (conv: Conversation) =>
    ConversationServiceBindings.Save(conv) as Promise<void>,
  load: (id: string) =>
    ConversationServiceBindings.Load(id) as Promise<Conversation>,
  list: () =>
    ConversationServiceBindings.List() as Promise<Conversation[]>,
  delete: (id: string) =>
    ConversationServiceBindings.Delete(id) as Promise<void>,
  generateId: () =>
    ConversationServiceBindings.GenerateConversationID() as Promise<string>,
  generateTitle: (firstMessage: string) =>
    ConversationServiceBindings.GenerateTitle(firstMessage) as Promise<string>,
  updateTitle: (id: string, title: string) =>
    ConversationServiceBindings.UpdateTitle(id, title) as Promise<void>,
};

export const taskService = {
  loadTasks: (projectRoot: string) =>
    TaskServiceBindings.LoadTasks(projectRoot) as Promise<TaskDef[]>,
};

export const workflowService = {
  loadWorkflows: (projectRoot: string) =>
    WorkflowServiceBindings.LoadWorkflows(projectRoot) as Promise<WorkflowDef[]>,
  loadWorkflow: (projectRoot: string, name: string) =>
    WorkflowServiceBindings.LoadWorkflow(projectRoot, name) as Promise<WorkflowDef>,
  validateDependencies: (wf: WorkflowDef) =>
    WorkflowServiceBindings.ValidateDependencies(wf) as Promise<void>,
  // N-55: Validate a single workflow and return structured errors.
  validateWorkflow: (wf: WorkflowDef) =>
    WorkflowServiceBindings.ValidateWorkflow(wf) as Promise<WorkflowValidationResult>,
  // N-55: Validate all workflows and return per-workflow results.
  validateAllWorkflows: (wfs: WorkflowDef[]) =>
    WorkflowServiceBindings.ValidateAllWorkflows(wfs) as Promise<WorkflowValidationResult[]>,
};

export const agentService = {
  execCommand: (command: string, cwd: string) =>
    AgentServiceBindings.ExecCommand(command, cwd) as Promise<ExecResult>,
  checkCommand: (command: string) =>
    AgentServiceBindings.CheckCommand(command) as Promise<CommandCheck>,
};

export const rulesService = {
  loadRules: (projectRoot: string) =>
    RulesServiceBindings.LoadRules(projectRoot) as Promise<RulesFile>,
  loadRulesMerge: (projectRoot: string) =>
    RulesServiceBindings.LoadRulesMerge(projectRoot) as Promise<RulesFile[]>,
  saveRules: (projectRoot: string, relPath: string, content: string) =>
    RulesServiceBindings.SaveRules(projectRoot, relPath, content) as Promise<void>,
  listCandidates: (projectRoot: string) =>
    RulesServiceBindings.ListRulesCandidates(projectRoot) as Promise<RulesFileCandidate[]>,
  loadRulesConfig: (projectRoot: string) =>
    RulesServiceBindings.LoadRulesConfig(projectRoot) as Promise<RulesConfig>,
  saveRulesConfig: (projectRoot: string, cfg: RulesConfig) =>
    RulesServiceBindings.SaveRulesConfig(projectRoot, cfg) as Promise<void>,
  saveUserRulesConfig: (cfg: RulesConfig) =>
    RulesServiceBindings.SaveUserRulesConfig(cfg) as Promise<void>,
};

export const logLevelService = {
  getLogPath: () =>
    LogLevelServiceBindings.GetLogPath() as Promise<string>,
  readLog: (maxBytes = 0) =>
    LogLevelServiceBindings.ReadLog(maxBytes) as Promise<string>,
};

export const pluginService = {
  listPlugins: (projectRoot: string) =>
    PluginServiceBindings.ListPlugins(projectRoot) as Promise<PluginInfo[]>,
  getPlugin: (name: string, projectRoot: string) =>
    PluginServiceBindings.GetPlugin(name, projectRoot) as Promise<PluginInfo>,
  setPluginEnabled: (name: string, enabled: boolean) =>
    PluginServiceBindings.SetPluginEnabled(name, enabled) as Promise<void>,
  readPluginFile: (pluginName: string, relPath: string, projectRoot: string) =>
    PluginServiceBindings.ReadPluginFile(pluginName, relPath, projectRoot) as Promise<string | null>,
};

export const profileService = {
  listProfiles: () =>
    ProfileServiceBindings.ListProfiles() as Promise<ProfileInfo[]>,
  getActiveProfile: () =>
    ProfileServiceBindings.GetActiveProfile() as Promise<string>,
  setActiveProfile: (name: string) =>
    ProfileServiceBindings.SetActiveProfile(name) as Promise<void>,
  createProfile: (name: string, fromCurrent: boolean) =>
    ProfileServiceBindings.CreateProfile(name, fromCurrent) as Promise<void>,
  deleteProfile: (name: string) =>
    ProfileServiceBindings.DeleteProfile(name) as Promise<void>,
  renameProfile: (oldName: string, newName: string) =>
    ProfileServiceBindings.RenameProfile(oldName, newName) as Promise<void>,
  setProfileDescription: (name: string, description: string) =>
    ProfileServiceBindings.SetProfileDescription(name, description) as Promise<void>,
  exportProfile: (name: string) =>
    ProfileServiceBindings.ExportProfile(name) as Promise<ProfileExport>,
  importProfile: (exportData: ProfileExport) =>
    ProfileServiceBindings.ImportProfile(exportData) as Promise<string>,
};

export const layoutService = {
  loadLayout: () =>
    LayoutServiceBindings.LoadLayout() as Promise<string>,
  saveLayout: (layoutJSON: string) =>
    LayoutServiceBindings.SaveLayout(layoutJSON) as Promise<void>,
  // Proposal H (prompt-4.md): Remove the persisted layout file.
  resetLayout: () =>
    LayoutServiceBindings.ResetLayout() as Promise<void>,
};
