// Re-export the auto-generated Wails bindings with TypeScript types.
// The bindings are regenerated by the Wails Vite plugin during dev/build
// and live in frontend/bindings/gugacode/.
import * as FileServiceBindings from "../../bindings/gugacode/services/fileservice.js";
import * as ProjectServiceBindings from "../../bindings/gugacode/services/projectservice.js";
import * as SettingsServiceBindings from "../../bindings/gugacode/services/settingsservice.js";
import * as WindowServiceBindings from "../../bindings/gugacode/services/windowservice.js";
import * as TerminalServiceBindings from "../../bindings/gugacode/services/terminalservice.js";
import * as AIServiceBindings from "../../bindings/gugacode/services/aiservice.js";
import * as GitServiceBindings from "../../bindings/gugacode/services/gitservice.js";
import * as SearchServiceBindings from "../../bindings/gugacode/services/searchservice.js";
import * as ConversationServiceBindings from "../../bindings/gugacode/services/conversationservice.js";
import * as TaskServiceBindings from "../../bindings/gugacode/services/taskservice.js";
import * as WorkflowServiceBindings from "../../bindings/gugacode/services/workflowservice.js";
import * as AgentServiceBindings from "../../bindings/gugacode/services/agentservice.js";
import * as RulesServiceBindings from "../../bindings/gugacode/services/rulesservice.js";
import * as LogLevelServiceBindings from "../../bindings/gugacode/services/loglevelservice.js";
import * as PluginServiceBindings from "../../bindings/gugacode/services/pluginservice.js";
import * as ProfileServiceBindings from "../../bindings/gugacode/services/profileservice.js";
import * as LayoutServiceBindings from "../../bindings/gugacode/services/layoutservice.js";
import * as ToolchainServiceBindings from "../../bindings/gugacode/services/toolchainservice.js";
import * as LSPServiceBindings from "../../bindings/gugacode/services/lspservice.js";
import * as MarketplaceServiceBindings from "../../bindings/gugacode/services/marketplaceservice.js";
// prompt-10: may need regen; Call.ByName fallback avoided — generate bindings after Go changes.
import * as DebugServiceBindings from "../../bindings/gugacode/services/debugservice.js";
import * as CoverageServiceBindings from "../../bindings/gugacode/services/coverageservice.js";
import type { DirEntry, Project, Settings, ChatMessage, GitFileChange, BranchInfo, SearchResult, Conversation, PresetMeta, PresetFile, PresetWithSource, CompletionRequest, CompletionResponse, RawCompletionResponse, BranchRef, MergeConflict, ReplaceResult, TaskDef, WorkflowDef, WorkflowValidationResult, ExecResult, CommandCheck, RulesFile, RulesFileCandidate, RulesConfig, PluginInfo, ProfileInfo, ProfileExport, SecretInfo, ToolchainCommand, ToolchainResult, LSPServerStatus, LSPCompletionRequest, LSPCompletionItem, Diagnostic, ProjectTemplate, CreateProjectRequest, ExtensionSearchResult, ExtensionDetail, InstalledExtension, VSCodeExtensionManifest } from "@/types";

export const fileService = {
  listDirectory: (path: string) =>
    FileServiceBindings.ListDirectory(path) as Promise<DirEntry[]>,
  // Plan 55: Quick Open — recursive file listing respecting .gitignore.
  listAllFiles: (rootPath: string) =>
    FileServiceBindings.ListAllFiles(rootPath) as Promise<string[]>,
  readFile: (path: string) =>
    FileServiceBindings.ReadFile(path) as Promise<string>,
  writeFile: (path: string, content: string) =>
    FileServiceBindings.WriteFile(path, content) as Promise<void>,
  createFile: (path: string) =>
    FileServiceBindings.CreateFile(path) as Promise<void>,
  createDirectory: (path: string) =>
    FileServiceBindings.CreateDirectory(path) as Promise<void>,
  deletePath: (path: string) =>
    FileServiceBindings.DeletePath(path) as Promise<void>,
  renamePath: (oldPath: string, newPath: string) =>
    FileServiceBindings.RenamePath(oldPath, newPath) as Promise<void>,
  pickDirectory: () =>
    FileServiceBindings.PickDirectory() as Promise<string>,
  revealInOS: (path: string) =>
    FileServiceBindings.RevealInOS(path) as Promise<void>,
};

export const projectService = {
  getRecentProjects: () =>
    ProjectServiceBindings.GetRecentProjects() as Promise<Project[]>,
  addProject: (path: string) =>
    ProjectServiceBindings.AddProject(path) as Promise<Project>,
  removeProject: (id: string) =>
    ProjectServiceBindings.RemoveProject(id) as Promise<void>,
  // G-FEAT-01: New Project scaffolding wizard.
  listProjectTemplates: () =>
    ProjectServiceBindings.ListProjectTemplates() as Promise<ProjectTemplate[]>,
  createProject: (req: CreateProjectRequest) =>
    ProjectServiceBindings.CreateProject(req as unknown as Parameters<typeof ProjectServiceBindings.CreateProject>[0]) as Promise<string>,
};

export const settingsService = {
  loadSettings: () =>
    SettingsServiceBindings.LoadSettings() as Promise<Settings>,
  saveSettings: (settings: Settings) =>
    SettingsServiceBindings.SaveSettings(settings as unknown as Parameters<typeof SettingsServiceBindings.SaveSettings>[0]) as Promise<void>,
  isAPIKeyEncryptedOnDisk: () =>
    SettingsServiceBindings.IsAPIKeyEncryptedOnDisk() as Promise<boolean>,
  getAPIKeyStorageMethod: () =>
    SettingsServiceBindings.GetAPIKeyStorageMethod() as Promise<string>,
  // N-49: list/delete keyring entries for orphan cleanup.
  listSecrets: () =>
    SettingsServiceBindings.ListSecrets() as Promise<SecretInfo[]>,
  deleteSecret: (account: string) =>
    SettingsServiceBindings.DeleteSecret(account) as Promise<void>,
  // Plan 11 Task 15: personalization asset storage (image upload/read/delete).
  // Wails bindings type Go []byte as string; cast at the boundary.
  savePersonalizationAsset: (filename: string, data: Uint8Array) =>
    SettingsServiceBindings.SavePersonalizationAsset(
      filename,
      data as unknown as string,
    ) as Promise<string>,
  readPersonalizationAsset: async (relPath: string): Promise<Uint8Array> => {
    const raw = await SettingsServiceBindings.ReadPersonalizationAsset(relPath);
    if (raw == null) return new Uint8Array(0);
    if (typeof raw === "string") {
      // Wails may deliver []byte as a binary/base64 string.
      try {
        const bin = atob(raw);
        const out = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
        return out;
      } catch {
        const out = new Uint8Array(raw.length);
        for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
        return out;
      }
    }
    return new Uint8Array(raw as unknown as ArrayLike<number>);
  },
  deletePersonalizationAsset: (relPath: string) =>
    SettingsServiceBindings.DeletePersonalizationAsset(relPath) as Promise<void>,
};

// prompt-6 Task 7: WindowService AI methods use regenerated ByID bindings
// (wails3 generate). No $Call.ByName remain for WindowService.
export const windowService = {
  minimise: () => WindowServiceBindings.Minimise(),
  maximise: () => WindowServiceBindings.Maximise(),
  // N-152: 标题栏放大/还原按钮共用一个控件，调用 ToggleMaximise 切换状态。
  toggleMaximise: () => WindowServiceBindings.ToggleMaximise(),
  // 查询当前窗口是否已最大化（用于初始化图标状态）。
  isMaximised: () => WindowServiceBindings.IsMaximised() as Promise<boolean>,
  close: () => WindowServiceBindings.Close(),
  toggleFullscreen: () => WindowServiceBindings.ToggleFullscreen(),
  setTitle: (title: string) => WindowServiceBindings.SetTitle(title),
  // prompt-4 Task 1: AI 独立窗口管理
  openAIWindow: () => WindowServiceBindings.OpenAIWindow() as Promise<void>,
  closeAIWindow: () => WindowServiceBindings.CloseAIWindow() as Promise<void>,
  toggleAIWindow: () => WindowServiceBindings.ToggleAIWindow() as Promise<void>,
  isAIWindowOpen: () => WindowServiceBindings.IsAIWindowOpen() as Promise<boolean>,
  setAIAlwaysOnTop: (onTop: boolean) =>
    WindowServiceBindings.SetAIAlwaysOnTop(onTop) as Promise<void>,
  isAIAlwaysOnTop: () => WindowServiceBindings.IsAIAlwaysOnTop() as Promise<boolean>,
  sendSelectionToAI: (code: string, language: string, filePath: string) =>
    WindowServiceBindings.SendSelectionToAI(code, language, filePath) as Promise<void>,
  openPathInExplorer: (path: string) =>
    WindowServiceBindings.OpenPathInExplorer(path) as Promise<void>,
  openPathInVSCode: (path: string) =>
    WindowServiceBindings.OpenPathInVSCode(path) as Promise<void>,
  focusMainWindow: () => WindowServiceBindings.FocusMainWindow() as Promise<void>,
};

export const terminalService = {
  start: (workingDir: string) =>
    TerminalServiceBindings.Start(workingDir) as Promise<void>,
  write: (input: string) =>
    TerminalServiceBindings.Write(input) as Promise<void>,
  kill: () => TerminalServiceBindings.Kill() as Promise<void>,
  isRunning: () =>
    TerminalServiceBindings.IsRunning() as Promise<boolean>,
  resize: (cols: number, rows: number) =>
    TerminalServiceBindings.Resize(cols, rows) as Promise<void>,
  startSession: (id: string, workingDir: string, shell: string) =>
    TerminalServiceBindings.StartSession(id, workingDir, shell) as Promise<void>,
  killSession: (id: string) =>
    TerminalServiceBindings.KillSession(id) as Promise<void>,
  writeSession: (id: string, input: string) =>
    TerminalServiceBindings.WriteSession(id, input) as Promise<void>,
  resizeSession: (id: string, cols: number, rows: number) =>
    TerminalServiceBindings.ResizeSession(id, cols, rows) as Promise<void>,
  isSessionRunning: (id: string) =>
    TerminalServiceBindings.IsSessionRunning(id) as Promise<boolean>,
  listSessions: () =>
    TerminalServiceBindings.ListSessions() as Promise<string[]>,
};

export const aiService = {
  // G-SEC-07: apiKey is optional. When omitted, useStoredKey=true tells the
  // backend to fetch the key from SettingsService via configId. The plaintext
  // key never crosses the Wails binding into the JS heap.
  setConfig: (config: {
    apiKey?: string;
    useStoredKey?: boolean;
    configId?: string;
    baseUrl: string;
    model: string;
    systemPrompt?: string;
    agentSystemPrompt?: string;
    conversationTitlePrompt?: string;
    inlineCompletionPrompt?: string;
    maxTokens?: number;
    contextWindow?: number;
    temperature?: number;
    protocol?: string; // "openai" | "anthropic"
    /** prompt-5 Task H: OpenAI-compatible tool definitions for native function calling. */
    tools?: Array<{
      type: "function";
      function: {
        name: string;
        description: string;
        parameters: Record<string, unknown>;
      };
    }>;
  }) =>
    AIServiceBindings.SetConfig({
      APIKey: config.apiKey ?? "",
      UseStoredKey: config.useStoredKey ?? false,
      ConfigID: config.configId ?? "",
      BaseURL: config.baseUrl,
      Model: config.model,
      SystemPrompt: config.systemPrompt ?? "",
      AgentSystemPrompt: config.agentSystemPrompt ?? "",
      ConversationTitlePrompt: config.conversationTitlePrompt ?? "",
      InlineCompletionPrompt: config.inlineCompletionPrompt ?? "",
      MaxTokens: config.maxTokens ?? 0,
      ContextWindow: config.contextWindow ?? 0,
      Temperature: config.temperature ?? 0,
      Protocol: config.protocol ?? "",
      // Bindings may not list Tools yet; cast at boundary.
      Tools: config.tools ?? [],
    } as unknown as Parameters<typeof AIServiceBindings.SetConfig>[0]) as Promise<void>,
  send: (messages: ChatMessage[]) =>
    AIServiceBindings.Send(messages) as Promise<{
      Content: string;
      FinishReason: string;
    } | null>,
  // prompt-6/7: StartStream returns streamId (bindings typed as string).
  startStream: (messages: ChatMessage[]) =>
    AIServiceBindings.StartStream(messages) as Promise<string>,
  stopStream: () =>
    AIServiceBindings.StopStream() as Promise<void>,
  getDefaultSystemPrompt: () =>
    AIServiceBindings.GetDefaultSystemPrompt() as Promise<string>,
  getAgentSystemPrompt: () =>
    AIServiceBindings.GetAgentSystemPrompt() as Promise<string>,
  getSystemPrompt: (name: string) =>
    AIServiceBindings.GetSystemPrompt(name) as Promise<string>,
  getConversationTitlePrompt: () =>
    AIServiceBindings.GetConversationTitlePrompt() as Promise<string>,
  getInlineCompletionSystemPrompt: () =>
    AIServiceBindings.GetInlineCompletionSystemPrompt() as Promise<string>,
  getEffectiveAgentSystemPrompt: () =>
    AIServiceBindings.GetEffectiveAgentSystemPrompt() as Promise<string>,
  getEffectiveConversationTitlePrompt: () =>
    AIServiceBindings.GetEffectiveConversationTitlePrompt() as Promise<string>,
  getEffectiveInlineCompletionPrompt: () =>
    AIServiceBindings.GetEffectiveInlineCompletionPrompt() as Promise<string>,
  generateTitleWithAI: (firstMessage: string) =>
    AIServiceBindings.GenerateTitleWithAI(firstMessage) as Promise<string>,
  getPresetPrompt: (name: string) =>
    AIServiceBindings.GetPresetPrompt(name) as Promise<string>,
  listPresets: () =>
    AIServiceBindings.ListPresets() as Promise<PresetMeta[]>,
  // N-50/Proposal S: Fetch available models from the provider's /v1/models endpoint.
  listModels: (baseURL: string, apiKey: string) =>
    AIServiceBindings.ListModels(baseURL, apiKey) as Promise<string[]>,
  listPresetsWithSource: () =>
    AIServiceBindings.ListPresetsWithSource() as Promise<PresetWithSource[]>,
  saveProjectPreset: (preset: PresetFile) =>
    AIServiceBindings.SaveProjectPreset(preset) as Promise<void>,
  saveUserPreset: (preset: PresetFile) =>
    AIServiceBindings.SaveUserPreset(preset) as Promise<void>,
  deleteProjectPreset: (name: string) =>
    AIServiceBindings.DeleteProjectPreset(name) as Promise<void>,
  deleteUserPreset: (name: string) =>
    AIServiceBindings.DeleteUserPreset(name) as Promise<void>,
  complete: (req: CompletionRequest, signal?: AbortSignal) => {
    // N-43: Preserve the CancellablePromise so the caller can abort the
    // in-flight request. Wails bindings return a CancellablePromise with
    // a .cancelOn(signal) method that binds cancellation to an AbortSignal.
    const cancellable = AIServiceBindings.Complete(req) as Promise<RawCompletionResponse> & {
      cancelOn?: (sig: AbortSignal) => Promise<RawCompletionResponse>;
    };
    if (signal && typeof (cancellable as { cancelOn?: unknown }).cancelOn === "function") {
      cancellable.cancelOn!(signal);
    }
    return cancellable.then((r: RawCompletionResponse) => ({ text: r.Text ?? r.text ?? "" })) as Promise<CompletionResponse>;
  },
};

export const gitService = {
  getStatus: (path: string) =>
    GitServiceBindings.GetStatus(path) as Promise<GitFileChange[]>,
  getBranchInfo: (path: string) =>
    GitServiceBindings.GetBranchInfo(path) as Promise<BranchInfo>,
  stage: (path: string, filePath: string) =>
    GitServiceBindings.Stage(path, filePath) as Promise<void>,
  unstage: (path: string, filePath: string) =>
    GitServiceBindings.Unstage(path, filePath) as Promise<void>,
  commit: (path: string, message: string) =>
    GitServiceBindings.Commit(path, message) as Promise<void>,
  getDiff: (path: string, filePath: string) =>
    GitServiceBindings.GetDiff(path, filePath) as Promise<string>,
  getFullDiff: (path: string) =>
    GitServiceBindings.GetFullDiff(path) as Promise<string>,
  listBranches: (path: string) =>
    GitServiceBindings.ListBranches(path) as Promise<BranchRef[]>,
  createBranch: (path: string, name: string) =>
    GitServiceBindings.CreateBranch(path, name) as Promise<void>,
  checkoutBranch: (path: string, name: string) =>
    GitServiceBindings.CheckoutBranch(path, name) as Promise<void>,
  deleteBranch: (path: string, name: string) =>
    GitServiceBindings.DeleteBranch(path, name) as Promise<void>,
  push: (repoPath: string) =>
    GitServiceBindings.Push(repoPath) as Promise<void>,
  pull: (repoPath: string) =>
    GitServiceBindings.Pull(repoPath) as Promise<void>,
  // G-FEAT-04: .gitignore template generation.
  gitignoreTemplate: (projectType: string) =>
    GitServiceBindings.GitignoreTemplate(projectType) as Promise<string>,
  createGitignore: (projectType: string) =>
    GitServiceBindings.CreateGitignore(projectType) as Promise<void>,
  // G-FEAT-04: rebase / merge conflict support.
  rebase: (branch: string) =>
    GitServiceBindings.Rebase(branch) as Promise<string>,
  abortRebase: () =>
    GitServiceBindings.AbortRebase() as Promise<void>,
  continueRebase: () =>
    GitServiceBindings.ContinueRebase() as Promise<void>,
  isRebaseInProgress: () =>
    GitServiceBindings.IsRebaseInProgress() as Promise<boolean>,
  listMergeConflicts: () =>
    GitServiceBindings.ListMergeConflicts() as Promise<MergeConflict[]>,
  resolveConflict: (filePath: string) =>
    GitServiceBindings.ResolveConflict(filePath) as Promise<void>,
};

export const searchService = {
  search: (root: string, query: string, ignoreCase: boolean) =>
    SearchServiceBindings.Search(root, query, ignoreCase) as Promise<SearchResult[]>,
  replace: (filePath: string, pattern: string, replacement: string, caseSensitive: boolean) =>
    SearchServiceBindings.Replace(filePath, pattern, replacement, caseSensitive) as Promise<ReplaceResult>,
};

export const conversationService = {
  save: (conv: Conversation) =>
    ConversationServiceBindings.Save(conv) as Promise<void>,
  load: (id: string) =>
    ConversationServiceBindings.Load(id) as Promise<Conversation>,
  list: () =>
    ConversationServiceBindings.List() as Promise<Conversation[]>,
  delete: (id: string) =>
    ConversationServiceBindings.Delete(id) as Promise<void>,
  generateId: () =>
    ConversationServiceBindings.GenerateConversationID() as Promise<string>,
  generateTitle: (firstMessage: string) =>
    ConversationServiceBindings.GenerateTitle(firstMessage) as Promise<string>,
  updateTitle: (id: string, title: string) =>
    ConversationServiceBindings.UpdateTitle(id, title) as Promise<void>,
};

export const taskService = {
  loadTasks: (projectRoot: string) =>
    TaskServiceBindings.LoadTasks(projectRoot) as Promise<TaskDef[]>,
};

export const workflowService = {
  loadWorkflows: (projectRoot: string) =>
    WorkflowServiceBindings.LoadWorkflows(projectRoot) as Promise<WorkflowDef[]>,
  loadWorkflow: (projectRoot: string, name: string) =>
    WorkflowServiceBindings.LoadWorkflow(projectRoot, name) as Promise<WorkflowDef>,
  // Frontend WorkflowDef uses string-union step types; bindings use enums —
  // cast at the Wails boundary (structural JSON is identical at runtime).
  validateDependencies: (wf: WorkflowDef) =>
    WorkflowServiceBindings.ValidateDependencies(
      wf as unknown as Parameters<typeof WorkflowServiceBindings.ValidateDependencies>[0],
    ) as Promise<void>,
  // N-55: Validate a single workflow and return structured errors.
  validateWorkflow: (wf: WorkflowDef) =>
    WorkflowServiceBindings.ValidateWorkflow(
      wf as unknown as Parameters<typeof WorkflowServiceBindings.ValidateWorkflow>[0],
    ) as Promise<WorkflowValidationResult>,
  // N-55: Validate all workflows and return per-workflow results.
  validateAllWorkflows: (wfs: WorkflowDef[]) =>
    WorkflowServiceBindings.ValidateAllWorkflows(
      wfs as unknown as Parameters<typeof WorkflowServiceBindings.ValidateAllWorkflows>[0],
    ) as Promise<WorkflowValidationResult[]>,
  // prompt-6 Task 7: workflow CRUD uses regenerated ByID bindings.
  createWorkflow: (projectRoot: string, name: string, def: WorkflowDef) =>
    WorkflowServiceBindings.CreateWorkflow(
      projectRoot,
      name,
      def as unknown as Parameters<typeof WorkflowServiceBindings.CreateWorkflow>[2],
    ) as Promise<void>,
  saveWorkflow: (projectRoot: string, name: string, def: WorkflowDef) =>
    WorkflowServiceBindings.SaveWorkflow(
      projectRoot,
      name,
      def as unknown as Parameters<typeof WorkflowServiceBindings.SaveWorkflow>[2],
    ) as Promise<void>,
  deleteWorkflow: (projectRoot: string, name: string) =>
    WorkflowServiceBindings.DeleteWorkflow(projectRoot, name) as Promise<void>,
  renameWorkflow: (projectRoot: string, oldName: string, newName: string) =>
    WorkflowServiceBindings.RenameWorkflow(projectRoot, oldName, newName) as Promise<void>,
};

export const agentService = {
  execCommand: (command: string, cwd: string) =>
    AgentServiceBindings.ExecCommand(command, cwd) as Promise<ExecResult>,
  checkCommand: (command: string) =>
    AgentServiceBindings.CheckCommand(command) as Promise<CommandCheck>,
};

export const rulesService = {
  loadRules: (projectRoot: string) =>
    RulesServiceBindings.LoadRules(projectRoot) as Promise<RulesFile>,
  loadRulesMerge: (projectRoot: string) =>
    RulesServiceBindings.LoadRulesMerge(projectRoot) as Promise<RulesFile[]>,
  saveRules: (projectRoot: string, relPath: string, content: string) =>
    RulesServiceBindings.SaveRules(projectRoot, relPath, content) as Promise<void>,
  listCandidates: (projectRoot: string) =>
    RulesServiceBindings.ListRulesCandidates(projectRoot) as Promise<RulesFileCandidate[]>,
  loadRulesConfig: (projectRoot: string) =>
    RulesServiceBindings.LoadRulesConfig(projectRoot) as Promise<RulesConfig>,
  saveRulesConfig: (projectRoot: string, cfg: RulesConfig) =>
    RulesServiceBindings.SaveRulesConfig(projectRoot, cfg) as Promise<void>,
  saveUserRulesConfig: (cfg: RulesConfig) =>
    RulesServiceBindings.SaveUserRulesConfig(cfg) as Promise<void>,
};

export const logLevelService = {
  getLogPath: () =>
    LogLevelServiceBindings.GetLogPath() as Promise<string>,
  readLog: (maxBytes = 0) =>
    LogLevelServiceBindings.ReadLog(maxBytes) as Promise<string>,
};

export const pluginService = {
  listPlugins: (projectRoot: string) =>
    PluginServiceBindings.ListPlugins(projectRoot) as Promise<PluginInfo[]>,
  getPlugin: (name: string, projectRoot: string) =>
    PluginServiceBindings.GetPlugin(name, projectRoot) as Promise<PluginInfo>,
  setPluginEnabled: (name: string, enabled: boolean) =>
    PluginServiceBindings.SetPluginEnabled(name, enabled) as Promise<void>,
  readPluginFile: (pluginName: string, relPath: string, projectRoot: string) =>
    PluginServiceBindings.ReadPluginFile(pluginName, relPath, projectRoot) as Promise<string | null>,
};

export const profileService = {
  listProfiles: () =>
    ProfileServiceBindings.ListProfiles() as Promise<ProfileInfo[]>,
  getActiveProfile: () =>
    ProfileServiceBindings.GetActiveProfile() as Promise<string>,
  setActiveProfile: (name: string) =>
    ProfileServiceBindings.SetActiveProfile(name) as Promise<void>,
  createProfile: (name: string, fromCurrent: boolean) =>
    ProfileServiceBindings.CreateProfile(name, fromCurrent) as Promise<void>,
  deleteProfile: (name: string) =>
    ProfileServiceBindings.DeleteProfile(name) as Promise<void>,
  renameProfile: (oldName: string, newName: string) =>
    ProfileServiceBindings.RenameProfile(oldName, newName) as Promise<void>,
  setProfileDescription: (name: string, description: string) =>
    ProfileServiceBindings.SetProfileDescription(name, description) as Promise<void>,
  exportProfile: (name: string) =>
    ProfileServiceBindings.ExportProfile(name) as Promise<ProfileExport>,
  importProfile: (exportData: ProfileExport) =>
    ProfileServiceBindings.ImportProfile(exportData) as Promise<string>,
};

export const layoutService = {
  loadLayout: () =>
    LayoutServiceBindings.LoadLayout() as Promise<string>,
  saveLayout: (layoutJSON: string) =>
    LayoutServiceBindings.SaveLayout(layoutJSON) as Promise<void>,
  // Proposal H (prompt-4.md): Remove the persisted layout file.
  resetLayout: () =>
    LayoutServiceBindings.ResetLayout() as Promise<void>,
};

export const toolchainService = {
  // G-FEAT-03: list available toolchain commands for the open workspace.
  listToolchainCommands: () =>
    ToolchainServiceBindings.ListToolchainCommands() as Promise<ToolchainCommand[]>,
  // G-FEAT-03: run a toolchain command by id. filePath, when provided,
  // runs the command in the file's directory (e.g. lint a single file).
  runToolchainCommand: (cmdId: string, filePath: string) =>
    ToolchainServiceBindings.RunToolchainCommand(cmdId, filePath) as Promise<ToolchainResult>,
  // G-FEAT-03: report which toolchain binaries are installed.
  detectToolchains: () =>
    ToolchainServiceBindings.DetectToolchains() as Promise<Record<string, boolean>>,
  // G-FEAT-03: push tool path overrides from Settings.ToolPaths to the backend.
  setToolPaths: (paths: Record<string, string>) =>
    ToolchainServiceBindings.SetToolPaths(paths) as Promise<void>,
  // prompt-9 9-C / 9-H / 9-I
  runTestAtCursor: (language: string, filePath: string, line: number, content: string) =>
    ToolchainServiceBindings.RunTestAtCursor(language, filePath, line, content) as Promise<ToolchainResult>,
  detectRuntimeVersions: () =>
    ToolchainServiceBindings.DetectRuntimeVersions() as Promise<{
      goVersion: string;
      nodeVersion: string;
      goplsVersion: string;
      hasGoWork: boolean;
    }>,
  setWorkspaceRoot: (root: string) =>
    ToolchainServiceBindings.SetWorkspaceRoot(root) as Promise<void>,
  // prompt-11 11-F
  runGoTestsJSON: (packageDir: string, runRegex: string) =>
    ToolchainServiceBindings.RunGoTestsJSON(packageDir, runRegex) as Promise<{
      success: boolean;
      output: string;
      events: Array<{ action: string; package?: string; test?: string; output?: string; elapsed?: number }>;
      statusByTest: Record<string, string>;
      durationMs: number;
    }>,
};

export const lspService = {
  // G-FEAT-02 / prompt-8: gopls + typescript-language-server / vtsls.
  detectServers: () =>
    LSPServiceBindings.DetectLSPServers() as Promise<LSPServerStatus[]>,
  startServer: (language: string) =>
    LSPServiceBindings.StartLSPServer(language) as Promise<void>,
  stopServer: (language: string) =>
    LSPServiceBindings.StopLSPServer(language) as Promise<void>,
  getCompletions: (req: LSPCompletionRequest) =>
    LSPServiceBindings.GetCompletions(req) as Promise<LSPCompletionItem[]>,
  getHover: (req: LSPCompletionRequest) =>
    LSPServiceBindings.GetHover(req) as Promise<string>,
  getDiagnostics: (req: LSPCompletionRequest) =>
    LSPServiceBindings.GetDiagnostics(req) as Promise<Diagnostic[]>,
  // prompt-8 M1/M2
  getDefinition: (req: LSPCompletionRequest) =>
    LSPServiceBindings.GetDefinition(req) as Promise<import("@/types").LSPLocation[]>,
  getReferences: (req: LSPCompletionRequest) =>
    LSPServiceBindings.GetReferences(req) as Promise<import("@/types").LSPLocation[]>,
  formatDocument: (req: LSPCompletionRequest) =>
    LSPServiceBindings.FormatDocument(req) as Promise<import("@/types").LSPTextEdit[]>,
  renameSymbol: (req: LSPCompletionRequest, newName: string) =>
    LSPServiceBindings.RenameSymbol(req, newName) as Promise<import("@/types").LSPTextEdit[]>,
  renameSymbolWorkspace: (req: LSPCompletionRequest, newName: string) =>
    LSPServiceBindings.RenameSymbolWorkspace(req, newName) as Promise<
      Array<{ filePath: string; edits: import("@/types").LSPTextEdit[] }>
    >,
  getSignatureHelp: (req: LSPCompletionRequest) =>
    LSPServiceBindings.GetSignatureHelp(req) as Promise<{
      label: string;
      documentation: string;
      parameters: string[];
      activeParameter: number;
      activeSignature: number;
    } | null>,
  organizeImports: (req: LSPCompletionRequest) =>
    LSPServiceBindings.OrganizeImports(req) as Promise<import("@/types").LSPTextEdit[]>,
  getCallStatus: (language: string) =>
    LSPServiceBindings.GetCallStatus(language) as Promise<{
      language: string;
      code: string;
      message: string;
    }>,
  closeDocument: (language: string, filePath: string) =>
    LSPServiceBindings.CloseDocument(language, filePath) as Promise<void>,
  didSaveDocument: (req: LSPCompletionRequest) =>
    LSPServiceBindings.DidSaveDocument(req) as Promise<void>,
};

// prompt-10/11: Delve DAP client (in-IDE)
type DebugSessionInfo = {
  running: boolean;
  address: string;
  mode: string;
  message: string;
  stopped?: boolean;
  stopReason?: string;
  threadId?: number;
};
type DebugStateSnapshot = {
  session: DebugSessionInfo;
  breakpoints: Array<{ id: number; file: string; line: number; verified: boolean }>;
  stack: Array<{ id: number; name: string; file: string; line: number; column: number }>;
  locals: Array<{ name: string; value: string; type: string }>;
};

export const debugService = {
  isAvailable: () => DebugServiceBindings.IsAvailable() as Promise<boolean>,
  statusMessage: () => DebugServiceBindings.StatusMessage() as Promise<string>,
  isRunning: () => DebugServiceBindings.IsRunning() as Promise<boolean>,
  getSession: () => DebugServiceBindings.GetSession() as Promise<DebugSessionInfo>,
  getState: () =>
    (DebugServiceBindings.GetState
      ? DebugServiceBindings.GetState()
      : DebugServiceBindings.GetSession().then((s: DebugSessionInfo) => ({
          session: s,
          breakpoints: [],
          stack: [],
          locals: [],
        }))) as Promise<DebugStateSnapshot>,
  launchPackage: (packageDir: string) =>
    DebugServiceBindings.LaunchPackage(packageDir) as Promise<DebugSessionInfo>,
  launchTest: (packageDir: string, runRegex: string) =>
    DebugServiceBindings.LaunchTest(packageDir, runRegex) as Promise<DebugSessionInfo>,
  stop: () => DebugServiceBindings.Stop() as Promise<void>,
  setBreakpoint: (file: string, line: number) =>
    DebugServiceBindings.SetBreakpoint(file, line) as Promise<{
      id: number;
      file: string;
      line: number;
      verified: boolean;
    }>,
  removeBreakpoint: (file: string, line: number) =>
    DebugServiceBindings.RemoveBreakpoint(file, line) as Promise<void>,
  toggleBreakpoint: (file: string, line: number) =>
    DebugServiceBindings.ToggleBreakpoint(file, line) as Promise<
      Array<{ id: number; file: string; line: number; verified: boolean }>
    >,
  listBreakpoints: () =>
    DebugServiceBindings.ListBreakpoints() as Promise<
      Array<{ id: number; file: string; line: number; verified: boolean }>
    >,
  continue: () => DebugServiceBindings.Continue() as Promise<void>,
  stepOver: () => DebugServiceBindings.StepOver() as Promise<void>,
  stepIn: () => DebugServiceBindings.StepIn() as Promise<void>,
  stepOut: () => DebugServiceBindings.StepOut() as Promise<void>,
  pause: () => DebugServiceBindings.Pause() as Promise<void>,
  refreshStackAndLocals: () => DebugServiceBindings.RefreshStackAndLocals() as Promise<void>,
  selectFrame: (frameId: number) => DebugServiceBindings.SelectFrame(frameId) as Promise<void>,
};

export const coverageService = {
  parseCoverProfile: (profilePath: string) =>
    CoverageServiceBindings.ParseCoverProfile(profilePath) as Promise<
      Array<{ file: string; line: number; covered: boolean }>
    >,
  runPackageCoverage: (packageDir: string) =>
    CoverageServiceBindings.RunPackageCoverage(packageDir) as Promise<{
      success: boolean;
      output: string;
      hits: Array<{ file: string; line: number; covered: boolean }>;
      profile: string;
      durationMs: number;
    }>,
  setWorkspaceRoot: (root: string) =>
    CoverageServiceBindings.SetWorkspaceRoot(root) as Promise<void>,
};

// G-VSC-01: VS Code extension marketplace client (Open VSX by default).
// Installed extensions live under <configDir>/gugacode/extensions/ and are
// disabled by default (G-SEC-12 req. 2). Downloads are SHA-256 verified
// (req. 3); a mismatch aborts the install.
export const marketplaceService = {
  // Search the registry for extensions matching a query. page is 1-based.
  searchExtensions: (query: string, page: number, pageSize: number) =>
    MarketplaceServiceBindings.SearchExtensions(query, page, pageSize) as Promise<ExtensionSearchResult[]>,
  // Fetch full metadata (categories, tags, versions, readme) for one extension.
  getExtensionDetail: (publisher: string, name: string) =>
    MarketplaceServiceBindings.GetExtensionDetail(publisher, name) as Promise<ExtensionDetail>,
  // Download, SHA-256 verify, and install a VSIX. Newly installed extensions
  // start disabled. Pass an empty version to install the latest.
  downloadAndInstallExtension: (publisher: string, name: string, version: string) =>
    MarketplaceServiceBindings.DownloadAndInstallExtension(publisher, name, version) as Promise<void>,
  // List locally installed extensions with their enabled state (sorted by
  // publisher then name). Missing state entries default to disabled.
  listInstalledExtensions: () =>
    MarketplaceServiceBindings.ListInstalledExtensions() as Promise<InstalledExtension[]>,
  // Remove an installed extension from disk and clear its enabled state.
  uninstallExtension: (publisher: string, name: string) =>
    MarketplaceServiceBindings.UninstallExtension(publisher, name) as Promise<void>,
  // Toggle the enabled/disabled state of an installed extension.
  setExtensionEnabled: (publisher: string, name: string, enabled: boolean) =>
    MarketplaceServiceBindings.SetExtensionEnabled(publisher, name, enabled) as Promise<void>,
  // Read and parse extension/package.json from an installed extension.
  getExtensionManifest: (publisher: string, name: string) =>
    MarketplaceServiceBindings.GetExtensionManifest(publisher, name) as Promise<VSCodeExtensionManifest>,
};
