// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "ai:chunk": string;
            "ai:done": string;
            "ai:error": string;
            "file:saved": string;
            "terminal:output": { [_ in string]?: string } | null;
            "time": string;
            "window:maximised": boolean;
        }
    }
}
