// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "agent:pending-updated": { [_ in string]?: any };
            "ai:apply-to-editor": { [_ in string]?: string };
            "ai:chunk": { [_ in string]?: any };
            "ai:done": { [_ in string]?: any };
            "ai:error": { [_ in string]?: any };
            "ai:selection": { [_ in string]?: string };
            "ai:stream-busy": { [_ in string]?: any };
            "ai:tool_calls": { [_ in string]?: any };
            "conversation:saved": { [_ in string]?: any };
            "file:saved": string;
            "settings:changed": { [_ in string]?: any };
            "terminal:output": { [_ in string]?: string };
            "time": string;
            "window:maximised": boolean;
        }
    }
}
