// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A Point is an X, Y coordinate pair. The axes increase right and down.
 */
export class Point {
    "X": number;
    "Y": number;

    /** Creates a new Point instance. */
    constructor($$source: Partial<Point> = {}) {
        if (!("X" in $$source)) {
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            this["Y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Point instance from a string or object.
     */
    static createFrom($$source: any = {}): Point {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Point($$parsedSource as Partial<Point>);
    }
}

/**
 * A Rectangle contains the points with Min.X <= X < Max.X, Min.Y <= Y < Max.Y.
 * It is well-formed if Min.X <= Max.X and likewise for Y. Points are always
 * well-formed. A rectangle's methods always return well-formed outputs for
 * well-formed inputs.
 * 
 * A Rectangle is also an [Image] whose bounds are the rectangle itself. At
 * returns color.Opaque for points in the rectangle and color.Transparent
 * otherwise.
 */
export class Rectangle {
    "Min": Point;
    "Max": Point;

    /** Creates a new Rectangle instance. */
    constructor($$source: Partial<Rectangle> = {}) {
        if (!("Min" in $$source)) {
            this["Min"] = (new Point());
        }
        if (!("Max" in $$source)) {
            this["Max"] = (new Point());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rectangle instance from a string or object.
     */
    static createFrom($$source: any = {}): Rectangle {
        const $$createField0_0 = $$createType0;
        const $$createField0_1 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Min" in $$parsedSource) {
            $$parsedSource["Min"] = $$createField0_0($$parsedSource["Min"]);
        }
        if ("Max" in $$parsedSource) {
            $$parsedSource["Max"] = $$createField0_1($$parsedSource["Max"]);
        }
        return new Rectangle($$parsedSource as Partial<Rectangle>);
    }
}

// Private type creation functions
const $$createType0 = Point.createFrom;
